# Generated by Django 4.0.6 on 2023-02-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='citytown/', verbose_name='Rasmi')),
                ('name', models.CharField(max_length=250, verbose_name='ismi')),
                ('prince', models.PositiveSmallIntegerField(verbose_name='narxi')),
                ('people', models.PositiveSmallIntegerField(verbose_name='odamlar')),
                ('phone', models.CharField(max_length=250, verbose_name='telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=250, verbose_name='adres')),
                ('lotation', models.TextField(verbose_name='lotatsiya')),
                ('days', models.PositiveSmallIntegerField(verbose_name='kunlar')),
                ('address_iframe', models.TextField(null=True, verbose_name='adres iframe')),
            ],
        ),
        migrations.CreateModel(
            name='Contient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contient/', verbose_name='Rasmi')),
                ('name', models.CharField(max_length=250, verbose_name='Ismi')),
            ],
        ),
        migrations.CreateModel(
            name='DealInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=250, verbose_name='ikon')),
                ('name', models.CharField(max_length=250, verbose_name='ismi')),
            ],
        ),
        migrations.CreateModel(
            name='NumberofGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ismi')),
            ],
        ),
        migrations.CreateModel(
            name='Price_Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startprice', models.PositiveSmallIntegerField(verbose_name="boshlang'ich narxi")),
                ('endprice', models.PositiveSmallIntegerField(verbose_name=' max narxi')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ismi')),
                ('phone', models.PositiveSmallIntegerField(verbose_name='telefon')),
                ('data', models.DateField(verbose_name='sana')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.citytown', verbose_name="yo'nalish")),
                ('numberofguest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.numberofguest', verbose_name='mehmon soni')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='country/', verbose_name='Rasmi')),
                ('name', models.CharField(max_length=250, verbose_name='ismi')),
                ('populations', models.PositiveSmallIntegerField(verbose_name='populyatsiyalar')),
                ('terytory', models.PositiveSmallIntegerField(verbose_name='hudud')),
                ('avg_price', models.PositiveSmallIntegerField(verbose_name='avg narxi')),
                ('title', models.CharField(max_length=250, verbose_name='yozuv')),
                ('map_image', models.ImageField(upload_to='map_image/', verbose_name='xarita rasmi')),
                ('total_guest_yearly', models.PositiveSmallIntegerField(verbose_name='yillik mehmonlar')),
                ('amazing_places', models.PositiveSmallIntegerField(verbose_name='ajoyib joylar')),
                ('amazing_acc', models.PositiveSmallIntegerField(verbose_name='ajoyib ass')),
                ('in_yearly', models.PositiveSmallIntegerField(verbose_name='yil ichida')),
                ('content', models.CharField(max_length=250, verbose_name='content')),
                ('cities_towns', models.ManyToManyField(to='home.citytown', verbose_name='mashhur joylari')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contient', verbose_name="qit'a")),
            ],
        ),
        migrations.AddField(
            model_name='citytown',
            name='deal_includes',
            field=models.ManyToManyField(to='home.dealinclude', verbose_name='kelishuvlar'),
        ),
    ]
