# Generated by Django 4.0.6 on 2022-12-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='citytown/')),
                ('name', models.CharField(max_length=250)),
                ('prince', models.PositiveSmallIntegerField()),
                ('people', models.PositiveSmallIntegerField()),
                ('phone', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('lotation', models.TextField()),
                ('days', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contient/')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DealInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='NumberofGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.PositiveSmallIntegerField()),
                ('data', models.DateField()),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.citytown')),
                ('numberofguest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.numberofguest')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='country/')),
                ('name', models.CharField(max_length=250)),
                ('populations', models.PositiveSmallIntegerField()),
                ('terytory', models.PositiveSmallIntegerField()),
                ('avg_price', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=250)),
                ('map_image', models.ImageField(upload_to='map_image/')),
                ('total_guest_yearly', models.PositiveSmallIntegerField()),
                ('amazing_places', models.PositiveSmallIntegerField()),
                ('amazing_acc', models.PositiveSmallIntegerField()),
                ('in_yearly', models.PositiveSmallIntegerField()),
                ('content', models.CharField(max_length=250)),
                ('cities_towns', models.ManyToManyField(to='home.citytown')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contient')),
            ],
        ),
        migrations.AddField(
            model_name='citytown',
            name='deal_includes',
            field=models.ManyToManyField(to='home.dealinclude'),
        ),
    ]
