# Generated by Django 4.0.6 on 2022-12-15 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_citytown_address_iframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startprice', models.PositiveSmallIntegerField(verbose_name="boshlang'ich narxi")),
                ('endprice', models.PositiveSmallIntegerField(verbose_name=' max narxi')),
            ],
        ),
        migrations.AlterField(
            model_name='citytown',
            name='address',
            field=models.CharField(max_length=250, verbose_name='adres'),
        ),
        migrations.AlterField(
            model_name='citytown',
            name='address_iframe',
            field=models.TextField(null=True, verbose_name='adres iframe'),
        ),
        migrations.AlterField(
            model_name='citytown',
            name='days',
            field=models.PositiveSmallIntegerField(verbose_name='kunlar'),
        ),
        migrations.AlterField(
            model_name='citytown',
            name='deal_includes',
            field=models.ManyToManyField(to='home.dealinclude', verbose_name='kelishuvlar'),
        ),
        migrations.AlterField(
            model_name='citytown',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='citytown',
            name='image',
            field=models.ImageField(upload_to='citytown/', verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='citytown',
            name='lotation',
            field=models.TextField(verbose_name='lotatsiya'),
        ),
        migrations.AlterField(
            model_name='citytown',
            name='name',
            field=models.CharField(max_length=250, verbose_name='ismi'),
        ),
        migrations.AlterField(
            model_name='citytown',
            name='people',
            field=models.PositiveSmallIntegerField(verbose_name='odamlar'),
        ),
        migrations.AlterField(
            model_name='citytown',
            name='phone',
            field=models.CharField(max_length=250, verbose_name='telefon'),
        ),
        migrations.AlterField(
            model_name='citytown',
            name='prince',
            field=models.PositiveSmallIntegerField(verbose_name='narxi'),
        ),
        migrations.AlterField(
            model_name='contient',
            name='image',
            field=models.ImageField(upload_to='contient/', verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='contient',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='country',
            name='amazing_acc',
            field=models.PositiveSmallIntegerField(verbose_name='ajoyib ass'),
        ),
        migrations.AlterField(
            model_name='country',
            name='amazing_places',
            field=models.PositiveSmallIntegerField(verbose_name='ajoyib joylar'),
        ),
        migrations.AlterField(
            model_name='country',
            name='avg_price',
            field=models.PositiveSmallIntegerField(verbose_name='avg narxi'),
        ),
        migrations.AlterField(
            model_name='country',
            name='cities_towns',
            field=models.ManyToManyField(to='home.citytown', verbose_name='mashhur joylari'),
        ),
        migrations.AlterField(
            model_name='country',
            name='content',
            field=models.CharField(max_length=250, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contient', verbose_name="qit'a"),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(upload_to='country/', verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='country',
            name='in_yearly',
            field=models.PositiveSmallIntegerField(verbose_name='yil ichida'),
        ),
        migrations.AlterField(
            model_name='country',
            name='map_image',
            field=models.ImageField(upload_to='map_image/', verbose_name='xarita rasmi'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=250, verbose_name='ismi'),
        ),
        migrations.AlterField(
            model_name='country',
            name='populations',
            field=models.PositiveSmallIntegerField(verbose_name='populyatsiyalar'),
        ),
        migrations.AlterField(
            model_name='country',
            name='terytory',
            field=models.PositiveSmallIntegerField(verbose_name='hudud'),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=250, verbose_name='yozuv'),
        ),
        migrations.AlterField(
            model_name='country',
            name='total_guest_yearly',
            field=models.PositiveSmallIntegerField(verbose_name='yillik mehmonlar'),
        ),
        migrations.AlterField(
            model_name='dealinclude',
            name='icon',
            field=models.CharField(max_length=250, verbose_name='ikon'),
        ),
        migrations.AlterField(
            model_name='dealinclude',
            name='name',
            field=models.CharField(max_length=250, verbose_name='ismi'),
        ),
        migrations.AlterField(
            model_name='numberofguest',
            name='name',
            field=models.CharField(max_length=250, verbose_name='ismi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='data',
            field=models.DateField(verbose_name='sana'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.citytown', verbose_name="yo'nalish"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=250, verbose_name='ismi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='numberofguest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.numberofguest', verbose_name='mehmon soni'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.PositiveSmallIntegerField(verbose_name='telefon'),
        ),
    ]
